# docker-compose.yml
    services:
      librarian:
        build:
          context: .
          dockerfile: Dockerfile
        container_name: librarian-service
        # Pass the model name from the .env file into the build process.
        args:
          - EMBEDDING_MODEL_NAME=${EMBEDDING_MODEL_NAME}
        restart: unless-stopped
        ports:
          - "8000:8000"
        env_file: .env
        secrets:
          - librarian_api_key
        environment:
          - LIBRARIAN_API_KEY_FILE=/run/secrets/librarian_api_key
          - REDIS_URL=redis://redis:6379/0
#          - OCI_CONFIG_PATH=/home/appuser/.oci/config
        depends_on:
          redis:
            condition: service_healthy
        networks:
          - librarian-net
        volumes:
#          - /opt/oci:/home/appuser/.oci:ro,z
          - librarian_chroma_data:/data/chroma
        healthcheck:
          test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
          interval: 30s
          timeout: 10s
          retries: 5
          start_period: 60s

      redis:
        image: redis:7.2-alpine
        container_name: librarian-redis
        restart: unless-stopped
        command: redis-server --save 60 1 --loglevel warning
        volumes:
          - librarian_redis_data:/data
        networks:
          - librarian-net
        healthcheck:
          test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
          interval: 10s
          timeout: 5s
          retries: 5

    networks:
      librarian-net:
        driver: bridge

    volumes:
      librarian_chroma_data: {}
      librarian_redis_data: {}

    secrets:
      librarian_api_key:
        file: ./secrets/librarian_api_key.txt
